language: c
compiler: clang

script:
    - cmake .
    - make

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libx11-dev libimlib2-dev libbsd-dev python3-sphinx

env:
  global:
    - secure: "kxg+hW70OZ0m/3BMrv3Wp5CAdLJrLv45v/QG/SHYjl2cI6kezucgxFTIpHBO/6qaOIPRhX407zbTDyUHRQbHcfi0wO9D9YEEYeawZRwsUlQlQVjztKnwQ5Y7fVDP6/0DhX/dFx++M51McPQlPcui2rIcw9vqPKgbcO8dKAUb4Bw="

addons:
  coverity_scan:
    project:
      name: "yabok/yawa"
      description: "Build submitted via Travis CI"
    notification_email: yawa@kyriasis.com
    build_command_prepend: cov-configure --template --comptype clangcc --compiler clang; cmake .
    build_command: make
    branch_pattern: coverity_scan
